

-- ----------------------------------------------
-- DDL Statements for tables
-- ----------------------------------------------

CREATE TABLE EVENTS (
	ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), 
	NAME VARCHAR(255), 
	DATE TIMESTAMP, 
	DESCRIPTION VARCHAR(255), 
	LOCATION VARCHAR(255), 
	REGISTRATIONLIMIT INTEGER,
	PRIMARY KEY (ID)
);
CREATE TABLE CUSTOMERS (
	ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), 
	NAME VARCHAR(255), 
	USERID VARCHAR(255), 
	PASSWORD VARCHAR(255),
	PRIMARY KEY (ID)
);
CREATE TABLE CUSTOMER_EVENT (
	CUSTOMER_ID INTEGER NOT NULL, 
	EVENT_ID INTEGER NOT NULL, 
	PRIMARY KEY (CUSTOMER_ID, EVENT_ID), 
	FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(ID) ON UPDATE CASCADE, 
	FOREIGN KEY (EVENT_ID) REFERENCES EVENTS(ID) ON UPDATE CASCADE 
);

-- ----------------------------------------------
-- DDL Statements for keys
-- ----------------------------------------------

-- primary/unique
--ALTER TABLE "EVENTS" ADD CONSTRAINT "SQL120325130144010" PRIMARY KEY ("ID");
--ALTER TABLE "CUSTOMERS" ADD CONSTRAINT "SQL120325130144011" PRIMARY KEY ("ID");

